version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansaju-app
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    networks:
      - ansaju_network
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:16-alpine
    restart: always
    container_name: ansaju-database
    shm_size: 128mb
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ansaju_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:

networks:
  ansaju_network:
    driver: bridge