services:
  db:
    image: postgres:16-alpine
    restart: no
    container_name: ansaju-database
    shm_size: 128mb
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
